# Permalinks
#
# Use of `relative_permalinks` no longer functions with jekyll
permalink:           /:categories/:year/:month/:day/:title/


# Setup
title:               'Hudson Bailey'
tagline:             'personal site & blog'
description:         'Go somewhere'
url:                 'hdbhdb.github.io'
baseurl:             ''
paginate:            5
highlighter:         rouge

# About/contact
author:
  name:              Hudson Bailey

# Custom vars
#version:             1.0.0


plugins:

   - jekyll-paginate
#remote_theme: poole/lanyon
