# Permalinks
#
# Use of `relative_permalinks` no longer functions with jekyll
permalink:           /blog/:categories/:year/:month/:day/:title/


# Setup
title:               'Hudson Bailey'
tagline:             ''
description:         ' '
url:                 'hdbhdb.github.io'
baseurl:             ''
paginate:            5
paginate_path:       '/blog/page:num/'
highlighter:         rouge

# About/contact
author:
  name:              Hudson Bailey

# Custom vars
#version:             1.0.0


plugins:
   - jekyll-redirect-from
   - jekyll-paginate
#remote_theme: poole/lanyon
