# Permalinks
#
# Use of `relative_permalinks` no longer functions with jekyll
permalink:           /:categories/:year/:month/:day/:title/


# Setup
title:               home page
tagline:             'under construction'
description:         'blog-to-be'
url:                 'hdbhdb.github.io'
baseurl:             ''
paginate:            5
highlighter:         rouge

# About/contact
author:
  name:              HB

# Custom vars
version:             1.0.0

#plugins:
#  - jekyll-remote-theme
#remote_theme: poole/lanyon
#remote_theme: poole
